### ISSUE TITLE
'code_spectrum' object has no attribute 'database'

### ISSUE THREAD

**Issue by ChuandongXie** [volkanozsarac/EzGM#10]
I tried to run example 2 but got AttributeError:

`'code_spectrum' object has no attribute 'database'`

I've checked the `code_spectrum()` class but cannot find any problem. The python version is 3.8.16. How to address this error?

**Comment by volkanozsarac** [comment]
Hi @ChuandongXie, it is a minor error that I have fixed recently. If you have installed EzGM from pip, this error is still here. Unfortunately, I did not have a chance to push the new version to PyPI. Please update your selection.py with the one here (on GitHub). I will soon push the corrected version. Then the errors on binder and google colab will be fixed as well.

Cheers,
Volkan

**Comment by ChuandongXie** [comment]
Thank you so much @volkanozsarac. Yes I installed EzGM from pip.  Now it works!
