### ISSUE TITLE
Practical usage of conditioning period Tstar as numpy.ndarray

### ISSUE THREAD

**Issue by Mengesh** [volkanozsarac/EzGM#14]
Hi @volkanozsarac, it's me again but with a whole different issue  :smile: 

`Tstar` variable is used in `ConditionalSpectrum.create` method as a conditioning period. The method description states that it can be also used as a `numpy.ndarray`, and its application is shown in [Example1.ipynb](https://github.com/volkanozsarac/EzGM/blob/master/Examples/binder/Example1.ipynb). However, I'm having a hard time figuring out the practical usage of having multiple conditioning periods like this. Could you please elaborate on this or at least point me to the literature where I can find the answer?

Thank you!

**Comment by volkanozsarac** [comment]
Hi @Mengesh, it is essentially used for different conditioning IM, AvgSA. I have written about this in my [thesis](https://www.researchgate.net/publication/375611529_Integrated_Evaluation_of_Earthquake-Induced_Economic_Losses_for_Multi-Span_Reinforced_Concrete_Bridges). You can check section 3.4.
