### ISSUE TITLE
Meta_Data: Sa_1, Sa_2 and RotD100

### ISSUE THREAD

**Issue by Mengesh** [volkanozsarac/EzGM#15]
Hi @volkanozsarac,

The README states that the metadata is actually a compilation of data from the flatfiles. I noticed that the NGA West2 flatfiles offer only `RotD50`. Therefore, I am curious whether you computed `Sa_1`, `Sa_2` (assuming they correspond to the original `H1` and `H2` of the record) and `RotD100` yourselves, or if you sourced them from somewhere else? Or perhaps I am misunderstanding something? :smile: 

Thank you!

**Comment by volkanozsarac** [comment]
> Hi @volkanozsarac,
> 
> 
> 
> The README states that the metadata is actually a compilation of data from the flatfiles. I noticed that the NGA West2 flatfiles offer only `RotD50`. Therefore, I am curious whether you computed `Sa_1`, `Sa_2` (assuming they correspond to the original `H1` and `H2` of the record) and `RotD100` yourselves, or if you sourced them from somewhere else? Or perhaps I am misunderstanding something? :smile: 
> 
> 
> 
> Thank you!

Hi, I believe I took it from Prof. Jack Baker's CS repository
